version: '3'
services:
#  mongodb:
#     image: mongo
#     ports:
#         - '27017:27017'
  mysql:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'